/*
 *  This is the home of function prototypes for all the global functions.
 */

#ifndef PROTO_H_INCLUDED
#define PROTO_H_INCLUDED

#ifdef STDC_HEADERS
#define P( x ) x
#else
#error Sorry, an ANSI C compiler is required now.
#endif

extern void
   ansiTransformExpress P( (char *, size_t)),
   ansiTransformPostHeader P( (char *, int)),
   arguments P( (int, char **)),
   configBbsRc P( (void)),
   colorConfig P( (void)),
   colorOptions P( (void)),
   connectBbs P( (void)),
   continuedDataHelper P( (void)),
   continuedPostHelper P( (void)),
   copyright P( (void)),
   deinitialize P( (void)),
   defaultColors P( (int)),
   editUsers P( (slist *, int ( *findfn )( const void *, const void * ), const char *)),
   expressColorConfig P( (void)),
   expressConfig P( (void)),
   expressFriendColorConfig P( (void)),
   expressUserColorConfig P( (void)),
   fatalExit P( (const char *, const char *)),
   fatalPerror P( (const char *, const char *)),
   feedPager P( ( int, ... ) ),
   filterExpress P( (int)),
   filterData P( (int)),
   filterPost P( (int)),
   filterUrl P( (const char *)),
   filterWhoList P( (int)),
   findHome P( (void)),
   flushInput P( (unsigned int)),
   generalColorConfig P( (void)),
   getFiveLines P( (int)),
   getString P( (int, char *, int)),
   handleInvalidInput P( (unsigned int *)),
   information P( (void)),
   initialize P( (const char *)),
   inputColorConfig P( (void)),
   killSsl P( (void)),
   license P( (void)),
   looper P( (void)),
   makeMessage P( (int)),
   morePromptHelper P( (void)),
   moveIfNeeded P( (const char *, const char *)),
   myExit P( (void)),
   mySleep P( (unsigned int)),
   newAwayMessage P( (void)),
   newMacro P( (int)),
   noTitleBar P( (void)),
   notReplyingTransformExpress P( (char *, size_t)),
   openBrowser P( (void)),
   openTmpFile P( (void)),
   otherInfo P( (void)),
   postColorConfig P( (void)),
   postFriendColorConfig P( (void)),
   postUserColorConfig P( (void)),
   readBbsRc P( (void)),
   replyCodeTransformExpress P( (char *, size_t)),
   replyMessage P( (void)),
   reprintLine P( (void)),
   resetTerm P( (void)),
   run P( (char *, char *)),
   saveBbsRc P( (void)),
   sendAnX P( (void)),
   sendBlock P( (void)),
   sendNaws P( (void)),
   setTerm P( (void)),
   sError P( (const char *, const char *)),
   setup P( (int)),
   sigInit P( (void)),
   sigOff P( (void)),
   sInfo P( (const char *, const char *)),
   slistDestroy P( (slist *)),
   slistDestroyItems P( (slist *)),
   slistSort P( (slist *)),
   smartErase P( (const char *)),
   smartPrint P( (const char *, const char *)),
   sPerror P( (const char *, const char *)),
   suspend P( (void)),
   techInfo P( (void)),
   telInit P( (void)),
   tempFileError P( (void)),
   titleBar P( (void)),
   trimTrailingWhitespace P( (char *)),
   truncateBbsRc P( (long)),
   warranty P( (void)),
   writeBbsRc P( (void));

extern int
   binarySearch P( (char *)),
   binarySort P( (void)),
   capPrintf P( ( const char *, ... ) ),
   capPutChar P( (int)),
   capPuts P( (const char *)),
   checkFile P( (FILE *)),
   colorize P( (const char *)),
   deleteQueue P( (queue *)),
   deleteFile P( (const char *)),
   extractNumber P( (const char *)),
   fSortCompare P( (const friend *const *, const friend *const *)),
   fSortCompareVoid P( (const void *, const void *)),
   fStrCompare P( (const char *, const friend *)),
   fStrCompareVoid P( (const void *, const void *)),
   getKey P( (void)),
   getWindowSize P( (void)),
   inKey P( (void)),
   isAutomaticReply P( (const char *)),
   isQueued P( (const char *, queue *)),
   more P( (int *, int)),
   netPrintf P( ( const char *, ... ) ),
   netPutChar P( (int)),
   netPuts P( (const char *)),
   newKey P( (int)),
   popQueue P( (char *, queue *)),
   prompt P( (FILE *, int *, int)),
   pushQueue P( (const char *, queue *)),
   readValidatedKey P( (const char *)),
   readNormalizedLine P( (FILE *, char *, size_t, int *, int *, const char *)),
   readValidatedMenuKey P( (const char *)),
   safeDeleteQueue P( (queue *)),
   slistAddItem P( (slist *, void *, int)),
   slistFind P( ( slist *, void *, int ( *findfn )( const void *, const void * ) ) ),
   slistRemoveItem P( (slist *, int)),
   smartName P( (char *, char *)),
   sortCompare P( (char **, char **)),
   sortCompareVoid P( (const void *, const void *)),
   strCompareVoid P( (const void *, const void *)),
   sPrompt P( (const char *, const char *, int)),
   stdPrintf P( ( const char *, ... ) ),
   stdPutChar P( (int)),
   stdPuts P( (const char *)),
   telReceive P( (int)),
   waitNextEvent P( (void)),
   yesNo P( (void)),
   yesNoDefault P( (int));

extern char
   ansiTransform P( (char)),
   ansiTransformPost P( (char, int)),
   backgroundPicker P( (void)),
   colorPicker P( (void)),
   expressColorMenu P( (void)),
   *extractName P( (const char *)),
   generalColorMenu P( (void)),
   *getName P( (int)),
   *findChar P( (const char *, int)),
   *duplicateString P( (const char *)),
   *findSubstring P( (const char *, const char *)),
   postColorMenu P( (void)),
   *strCtrl P( (int)),
   *stripAnsi P( (char *, size_t)),
   userOrFriend P( (void));

extern FILE
   *findBbsRc P( (void)),
   *openBbsRc P( (void)),
   *openBbsFriends P( (void)),
   *findBbsFriends P( (void));

extern queue
   *newQueue P( (int, int));

extern slist
   *slistCreate P( ( int, int ( *sortfn )( const void *, const void * ), ... ) ),
   *slistIntersection P( (const slist *, const slist *));

extern RETSIGTYPE
   bye P( (int)),
   naws P( (int)),
   reapChild P( (int));

#endif /* PROTO_H_INCLUDED */
